org: snowcait
app: tweet-album
service: tweet-album
frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs18.x
  memorySize: 128
  architecture: arm64
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - '*'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  auth:
    handler: handler.auth
    events:
      - httpApi:
          method: POST
          path: /auth
