org: snowcait
app: tweet-album
service: tweet-album
frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs18.x
  memorySize: 128
  architecture: arm64
  httpApi:
    cors: true
    authorizers:
      twitterAuthorizer:
        type: request
        functionName: authorizer
        enableSimpleResponses: true
        resultTtlInSeconds: 3600
        identitySource:
          - $request.header.Authorization
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - '*'
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
            - Fn::GetAtt: [ AlbumsTable, Arn ]
  environment:
    NODE_OPTIONS: --experimental-fetch
    users_table:
      Ref: UsersTable
    albums_table:
      Ref: AlbumsTable

functions:
  authorizer:
    handler: handler.authorizer
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  auth:
    handler: handler.auth
    events:
      - httpApi:
          method: POST
          path: /auth
  saveAlbum:
    handler: handler.saveAlbum
    events:
      - httpApi:
          method: POST
          path: /albums
          authorizer:
            name: twitterAuthorizer
  listAlbums:
    handler: handler.listAlbums
    events:
      - httpApi:
          method: GET
          path: /{userId}/albums
  updateAlbums:
    handler: handler.updateAlbums
    # events:
    #   - eventBridge:
    #       schedule: rate(1 hour)

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-users-${sls:stage}
        AttributeDefinitions:
          - AttributeName: twitterUserId
            AttributeType: S
        KeySchema:
          - AttributeName: twitterUserId
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    AlbumsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-albums-${sls:stage}
        AttributeDefinitions:
          - AttributeName: twitterUserId
            AttributeType: S
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: twitterUserId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
