name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-api.yml
      - api/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: api

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: npm install -g serverless
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ap-northeast-1
      - run: npm ci
        env:
          NODE_ENV: production
      - run: npm ls
      - run: serverless deploy --verbose
